/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Home */
        get: operations["admin_home__get"];
        put?: never;
        /** Admin Login */
        post: operations["admin_login__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Users */
        get: operations["get_users_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_users__user_id__get"];
        /** Update User */
        put: operations["update_user_users__user_id__put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movies */
        get: operations["list_movies_movies_get"];
        put?: never;
        /** Create Movie */
        post: operations["create_movie_movies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movie_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Movie */
        get: operations["get_movie_movies__movie_id__get"];
        put?: never;
        post?: never;
        /** Delete Movie */
        delete: operations["delete_movie_movies__movie_id__delete"];
        options?: never;
        head?: never;
        /** Update Movie */
        patch: operations["update_movie_movies__movie_id__patch"];
        trace?: never;
    };
    "/screenings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Screenings */
        get: operations["list_screenings_screenings_get"];
        put?: never;
        /** Create Screening */
        post: operations["create_screening_screenings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screenings/{screening_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screening */
        get: operations["get_screening_screenings__screening_id__get"];
        put?: never;
        post?: never;
        /** Delete Screening */
        delete: operations["delete_screening_screenings__screening_id__delete"];
        options?: never;
        head?: never;
        /** Update Screening */
        patch: operations["update_screening_screenings__screening_id__patch"];
        trace?: never;
    };
    "/screenings/{screening_id}/sale/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Screening Sale */
        post: operations["open_screening_sale_screenings__screening_id__sale_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screenings/{screening_id}/sale/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Screening Sale */
        post: operations["close_screening_sale_screenings__screening_id__sale_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auditoriums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Auditoriums */
        get: operations["list_auditoriums_auditoriums_get"];
        put?: never;
        /** Create Auditorium */
        post: operations["create_auditorium_auditoriums_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auditoriums/{auditorium_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auditorium */
        get: operations["get_auditorium_auditoriums__auditorium_id__get"];
        put?: never;
        post?: never;
        /** Delete Auditorium */
        delete: operations["delete_auditorium_auditoriums__auditorium_id__delete"];
        options?: never;
        head?: never;
        /** Update Auditorium */
        patch: operations["update_auditorium_auditoriums__auditorium_id__patch"];
        trace?: never;
    };
    "/auditoriums/{auditorium_id}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seats */
        get: operations["get_seats_auditoriums__auditorium_id__seats_get"];
        /** Replace Seats */
        put: operations["replace_seats_auditoriums__auditorium_id__seats_put"];
        /** Create Seat */
        post: operations["create_seat_auditoriums__auditorium_id__seats_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auditoriums/{auditorium_id}/seats/{seat_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seat */
        get: operations["get_seat_auditoriums__auditorium_id__seats__seat_id__get"];
        put?: never;
        post?: never;
        /** Delete Seat */
        delete: operations["delete_seat_auditoriums__auditorium_id__seats__seat_id__delete"];
        options?: never;
        head?: never;
        /** Update Seat */
        patch: operations["update_seat_auditoriums__auditorium_id__seats__seat_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** AuditoriumCreateSchema */
        AuditoriumCreateSchema: {
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** AuditoriumResponse */
        AuditoriumResponse: {
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Capacity */
            total_capacity: number;
            /** Is Accessible */
            is_accessible: boolean;
        };
        /** AuditoriumUpdateSchema */
        AuditoriumUpdateSchema: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** AuditoriumWithSeats */
        AuditoriumWithSeats: {
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Capacity */
            total_capacity: number;
            /** Is Accessible */
            is_accessible: boolean;
            /** Seats */
            seats: components["schemas"]["SeatResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MovieCreateSchema */
        MovieCreateSchema: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            rating: components["schemas"]["MovieRating"];
            /** Release Date */
            release_date?: string | null;
            status: components["schemas"]["MovieStatus"];
        };
        /**
         * MovieRating
         * @enum {string}
         */
        MovieRating: "G" | "PG" | "PG-13" | "R";
        /** MovieResponseSchema */
        MovieResponseSchema: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Duration Minutes */
            duration_minutes: number;
            rating: components["schemas"]["MovieRating"];
            /** Release Date */
            release_date?: string | null;
            status: components["schemas"]["MovieStatus"];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MovieStatus
         * @enum {string}
         */
        MovieStatus: "draft" | "now_showing" | "archived";
        /** MovieUpdateSchema */
        MovieUpdateSchema: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            rating?: components["schemas"]["MovieRating"] | null;
            /** Release Date */
            release_date?: string | null;
            status?: components["schemas"]["MovieStatus"] | null;
        };
        /** ScreeningCreate */
        ScreeningCreate: {
            /** Movie Id */
            movie_id: number;
            /** Auditorium Id */
            auditorium_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Price */
            price: number | string;
            status: components["schemas"]["ScreeningStatus"];
        };
        /** ScreeningResponse */
        ScreeningResponse: {
            /** Id */
            id: number;
            /** Movie Id */
            movie_id: number;
            /** Auditorium Id */
            auditorium_id: number;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /** Price */
            price: string;
            status: components["schemas"]["ScreeningStatus"];
        };
        /**
         * ScreeningStatus
         * @enum {string}
         */
        ScreeningStatus: "draft" | "on_sale" | "past" | "cancelled";
        /** ScreeningUpdate */
        ScreeningUpdate: {
            /** Movie Id */
            movie_id?: number | null;
            /** Auditorium Id */
            auditorium_id?: number | null;
            /** Start Time */
            start_time?: string | null;
            /** Price */
            price?: number | string | null;
            status?: components["schemas"]["ScreeningStatus"] | null;
        };
        /** SeatBase */
        SeatBase: {
            /** Row */
            row: string;
            /** Number */
            number: number;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
            /**
             * Is Accessible
             * @default true
             */
            is_accessible: boolean;
            /** X Pos */
            x_pos: number;
            /** Y Pos */
            y_pos: number;
            /**
             * Angle
             * @default 0
             */
            angle: number;
        };
        /** SeatResponse */
        SeatResponse: {
            /** Row */
            row: string;
            /** Number */
            number: number;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
            /**
             * Is Accessible
             * @default true
             */
            is_accessible: boolean;
            /** X Pos */
            x_pos: number;
            /** Y Pos */
            y_pos: number;
            /**
             * Angle
             * @default 0
             */
            angle: number;
            /** Id */
            id: number;
            /** Auditorium Id */
            auditorium_id: number;
        };
        /** SeatUpdate */
        SeatUpdate: {
            /** Row */
            row?: string | null;
            /** Number */
            number?: number | null;
            /** Is Available */
            is_available?: boolean | null;
            /** Is Accessible */
            is_accessible?: boolean | null;
            /** X Pos */
            x_pos?: number | null;
            /** Y Pos */
            y_pos?: number | null;
            /** Angle */
            angle?: number | null;
        };
        /** UserCreateSchema */
        UserCreateSchema: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string | null;
            /** Password */
            password: string;
        };
        /** UserResponseSchema */
        UserResponseSchema: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Phone */
            phone: string | null;
            /** Password */
            password: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserUpdateSchema */
        UserUpdateSchema: {
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Password */
            password?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    admin_login__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseSchema"][];
                };
            };
        };
    };
    create_user_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movies_movies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieResponseSchema"][];
                };
            };
        };
    };
    create_movie_movies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_movie_movies__movie_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_movie_movies__movie_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_movie_movies__movie_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movie_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_screenings_screenings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"][];
                };
            };
        };
    };
    create_screening_screenings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_screening_screenings__screening_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_screening_screenings__screening_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_screening_screenings__screening_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScreeningUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_screening_sale_screenings__screening_id__sale_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_screening_sale_screenings__screening_id__sale_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screening_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreeningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_auditoriums_auditoriums_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumResponse"][];
                };
            };
        };
    };
    create_auditorium_auditoriums_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditoriumCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auditorium_auditoriums__auditorium_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_auditorium_auditoriums__auditorium_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_auditorium_auditoriums__auditorium_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditoriumUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seats_auditoriums__auditorium_id__seats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumWithSeats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_seats_auditoriums__auditorium_id__seats_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatBase"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriumWithSeats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_seat_auditoriums__auditorium_id__seats_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seat_auditoriums__auditorium_id__seats__seat_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
                seat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_seat_auditoriums__auditorium_id__seats__seat_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
                seat_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_seat_auditoriums__auditorium_id__seats__seat_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                auditorium_id: number;
                seat_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeatUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
